version: 0.2

        
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install awscli cfn-lint
  build:
    commands:
      - aws cloudformation validate-template --template-body file://core.yaml
      - cfn-lint --cfn_file core.yaml
  post_build:
    commands:
      - aws cloudformation deploy --template-file core.yaml --stack-name corepipe --parameter-overrides VpcCidr=10.0.0.0/16 Environment=test
      - python3 core_test.py
    finally:
      -  aws cloudformation delete-stack --stack-name corepipe

  # post_build:
  #   run-as: Linux-user-name
  #   commands:
  #     - command
  #     - command
  #   finally:
  #     - command
  #     - command
# reports:
#   report-group-name-or-arn:
#     files:
#       - location
#       - location
#     base-directory: location
#     discard-paths: no | yes
#     file-format: report-format
# artifacts:
#   files:
#     - location
#     - location
